<<<XML
<program xmlns="http://www.hodex.nl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.hodex.nl http://www.hodex.nl/hodex.xsd"><editor><![CDATA[editor@hodexer.nl]]></editor><expires>2012-02-13</expires><generator><![CDATA[hodexer]]></generator><hodexVersion><![CDATA[2.5.8]]></hodexVersion><lastEdited>2012-02-03</lastEdited><programClassification><crohoCode xsi:nil='true'></crohoCode><degree>PhD</degree><fieldOfEducation classification='SOI2006'>5131</fieldOfEducation><financing>government</financing><numerusFixus xsi:nil='true'></numerusFixus><orgUnitId>uva</orgUnitId><orgUnitLocation><![CDATA[Amsterdam]]></orgUnitLocation><programCredits>0</programCredits><programDuration unit="month">0</programDuration><programForm>full-time</programForm><programId>845</programId><programLevel>PhD</programLevel><programType>regular</programType><startingYear>2012</startingYear><studyCluster>religion and philosophy</studyCluster></programClassification><programContacts></programContacts><programCurriculum><instructionLanguage><languageCode>en</languageCode><percentage>100</percentage></instructionLanguage><percentageDistanceLearning xsi:nil='true'></percentageDistanceLearning><percentageNightEducation xsi:nil='true'></percentageNightEducation><sizeOfTutorialGroups xsi:nil='true'></sizeOfTutorialGroups><teachingTypesInCurriculumYear year='1'><teachingTypeInCurriculum><typeOfTeaching>theory</typeOfTeaching>
<percentage>0</percentage></teachingTypeInCurriculum><teachingTypeInCurriculum><typeOfTeaching>practice</typeOfTeaching>
<percentage>0</percentage></teachingTypeInCurriculum><teachingTypeInCurriculum><typeOfTeaching>self study</typeOfTeaching>
<percentage>0</percentage></teachingTypeInCurriculum></teachingTypesInCurriculumYear></programCurriculum><programDescriptions><contentLink><contentSummary xml:lang="en"><![CDATA[€ 4000 per year]]></contentSummary><contentType>website</contentType><subject>tuition fee</subject><webLink xml:lang="en"><![CDATA[http://studieadres.nl]]></webLink></contentLink><programDescription xml:lang="en"><![CDATA[The ILLC's PhD programme in Logic is one of the most prestigious in the world. The educational programme includes course work, seminars, colloquia and a visit to a relevant Summer School. 


The student takes part in current ILLC research projects and has all the advantages of this flourishing scientific community. The emphasis of the PhD programme lies on training the student to become an independent researcher. Many ILLC PhD-graduates occupy key positions in academic and industrial environments.

]]></programDescription><programName xml:lang="en"><![CDATA[Logic (PhD)]]></programName><programName xml:lang="nl"><![CDATA[Logic (PhD)]]></programName><programSummary xml:lang="en"><![CDATA[The ILLC's PhD programme in Logic is one of the most prestigious in the world. The educational programme includes course work, seminars, colloquia and a visit to a relevant Summer School. ]]></programSummary><searchword xml:lang="nl"></searchword><webLink xml:lang="en">http://www.illc.uva.nl/MScLogic/programs/</webLink><webLink xml:lang="nl">http://www.illc.uva.nl/MScLogic/programs/</webLink></programDescriptions><programInternationalization><ErasmusMundusProgram>0</ErasmusMundusProgram><facilitationForeignScholarships xsi:nil='true'></facilitationForeignScholarships><foreignStay xsi:nil='true'></foreignStay><maxForeignCredits xsi:nil='true'></maxForeignCredits><percentageForeignStudents xsi:nil='true'></percentageForeignStudents><percentageForeignTeachers xsi:nil='true'></percentageForeignTeachers><percentageStudentsAbroad xsi:nil='true'></percentageStudentsAbroad><percentageTeachersAbroad xsi:nil='true'></percentageTeachersAbroad><studyAbroad xsi:nil='true'></studyAbroad></programInternationalization><programRelations></programRelations><programOrganization><faculty xml:lang="en">Faculty of Science</faculty><faculty xml:lang="nl">faculteit der Natuurwetenschappen, Wiskunde en Informatica</faculty><programRun><applicationDeadline>2012-04-01</applicationDeadline><applicationDeadlineNonEU>2012-02-01</applicationDeadlineNonEU><endDate>2012-09-01</endDate><startingDate>2012-09-01</startingDate></programRun><programRun><applicationDeadline>2013-04-01</applicationDeadline><applicationDeadlineNonEU>2013-02-01</applicationDeadlineNonEU><endDate>2013-09-01</endDate><startingDate>2013-09-01</startingDate></programRun><programRun><applicationDeadline>2014-04-01</applicationDeadline><applicationDeadlineNonEU>2014-02-01</applicationDeadlineNonEU><endDate>2014-09-01</endDate><startingDate>2014-09-01</startingDate></programRun><programStart><applicationDeadline>April</applicationDeadline><applicationDeadlineNonEU>February</applicationDeadlineNonEU><startingMonth>September</startingMonth></programStart></programOrganization><programFree><crohoName></crohoName><dl>en</dl><studyClusterUvA>Filosofie en Religie</studyClusterUvA><pp></pp><ps></ps><cq></cq><cp></cp><orgUnitLocationId><![CDATA[Amsterdam]]></orgUnitLocationId><facultyId><![CDATA[nwi]]></facultyId><targetMarket>nl</targetMarket><targetMarket>int</targetMarket><programPhase>initial</programPhase></programFree></program>
XML;