<<<XML
<program xmlns="http://www.hodex.nl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.hodex.nl http://www.hodex.nl/hodex.xsd"><editor><![CDATA[editor@hodexer.nl]]></editor><expires>2012-02-13</expires><generator><![CDATA[hodexer]]></generator><hodexVersion><![CDATA[2.5.8]]></hodexVersion><lastEdited>2012-02-03</lastEdited><programClassification><accreditation><accreditationDate>2014-12-31</accreditationDate><orgUnitCountry>nl</orgUnitCountry><orgUnitName><![CDATA[NVAO]]></orgUnitName><webLink xml:lang='nl'>http://www.nvao.net</webLink></accreditation><crohoCode>60202</crohoCode><degree>MSc</degree><fieldOfEducation classification='SOI2006'>5141</fieldOfEducation><financing>government</financing><numerusFixus xsi:nil='true'></numerusFixus><orgUnitId>uva</orgUnitId><orgUnitLocation><![CDATA[Amsterdam]]></orgUnitLocation><programCredits>120</programCredits><programDuration unit="month">24</programDuration><programForm>full-time</programForm><programId>1014</programId><programLevel>academic master</programLevel><programType>regular</programType><startingYear>2012</startingYear><studyCluster>technology</studyCluster><studyCluster>nature</studyCluster></programClassification><programContacts></programContacts><programCurriculum><instructionLanguage><languageCode>en</languageCode><percentage>100</percentage></instructionLanguage><percentageDistanceLearning>0</percentageDistanceLearning><percentageNightEducation>0</percentageNightEducation><sizeOfTutorialGroups xsi:nil='true'></sizeOfTutorialGroups><teachingTypesInCurriculumYear year='1'><teachingTypeInCurriculum><typeOfTeaching>theory</typeOfTeaching><percentage>0</percentage></teachingTypeInCurriculum><teachingTypeInCurriculum><typeOfTeaching>practice</typeOfTeaching><percentage>0</percentage></teachingTypeInCurriculum><teachingTypeInCurriculum><typeOfTeaching>self study</typeOfTeaching><percentage>0</percentage></teachingTypeInCurriculum></teachingTypesInCurriculumYear></programCurriculum><programDescriptions><contentLink><contentSummary xml:lang="nl"><![CDATA[Graduates can apply for PhD positions at biomedical physics and biophysics research institutes and hospitals around the world. Other career options include scientific positions at various government institutions, laboratories of major Dutch-based international corporations or research institutes.

The programme's emphasis on analytical thinking provides an excellent foundation for a career in software development and IT, investment banking, consultancy or politics.]]></contentSummary><contentType>website</contentType><subject>job perspective</subject><webLink xml:lang="nl"><![CDATA[http://studieadres.nl]]></webLink></contentLink><programDescription xml:lang="nl"><![CDATA[The programme is for students interested in one or more of the following subjects:

■the study of physical processes in the human body, organs, cells and macromolecules;
■the use of advanced biophysical methods to study macromolecules at the single-molecule level and to study biological processes down to femtosecond timescales;
■the development and improvement of technology for medical diagnostics and therapy;
■the interaction of light and/or radiation with cells and tissues (biomedical photonics);
■the manipulation of tissues and cells by light or radiation to improve diagnosis and monitoring.

This Master's track offers the chance to reflect on research topics such as: 
■the quest for quantitative functional monitoring and imaging of living tissue;
■working in multidisciplinary research teams with physicists, chemists, biologists, engineers and medical professionals; 
■theoretical knowledge and hands-on experience in biomedical imaging, molecular and cellular biophysics and photonics;
■research and development of new methods for diagnosis and monitoring.]]></programDescription><programDescription xml:lang="en"><![CDATA[The programme is for students interested in one or more of the following subjects:

■the study of physical processes in the human body, organs, cells and macromolecules;
■the use of advanced biophysical methods to study macromolecules at the single-molecule level and to study biological processes down to femtosecond timescales;
■the development and improvement of technology for medical diagnostics and therapy;
■the interaction of light and/or radiation with cells and tissues (biomedical photonics);
■the manipulation of tissues and cells by light or radiation to improve diagnosis and monitoring.

This Master's track offers the chance to reflect on research topics such as: 
■the quest for quantitative functional monitoring and imaging of living tissue;
■working in multidisciplinary research teams with physicists, chemists, biologists, engineers and medical professionals; 
■theoretical knowledge and hands-on experience in biomedical imaging, molecular and cellular biophysics and photonics;
■research and development of new methods for diagnosis and monitoring.]]></programDescription><programName xml:lang="nl"><![CDATA[Physics: Physics of Life and Health]]></programName><programName xml:lang="en"><![CDATA[Physics: Physics of Life and Health]]></programName><programSummary xml:lang="en"><![CDATA[Physics of Life and Health is a track of the Master's programme in Physics.]]></programSummary><programSummary xml:lang="nl"><![CDATA[Physics of Life and Health is a track of the Master's programme in Physics.]]></programSummary><searchword xml:lang="nl"></searchword><webLink xml:lang="nl">http://www.studeren.uva.nl/msc-life-and-health</webLink><webLink xml:lang="en">http://studeren.uva.nl/msc_life_and_health</webLink></programDescriptions><programInternationalization><ErasmusMundusProgram>0</ErasmusMundusProgram><facilitationForeignScholarships xsi:nil='true'></facilitationForeignScholarships><foreignStay>0</foreignStay><maxForeignCredits xsi:nil='true'></maxForeignCredits><percentageForeignStudents xsi:nil='true'></percentageForeignStudents><percentageForeignTeachers xsi:nil='true'></percentageForeignTeachers><percentageStudentsAbroad xsi:nil='true'></percentageStudentsAbroad><percentageTeachersAbroad xsi:nil='true'></percentageTeachersAbroad><studyAbroad xsi:nil='true'></studyAbroad></programInternationalization><programRelations></programRelations><programOrganization><faculty xml:lang="en">Faculty of Science</faculty><faculty xml:lang="nl">faculteit der Natuurwetenschappen, Wiskunde en Informatica</faculty><programRun><applicationDeadline xsi:nil="true"/><applicationDeadlineNonEU xsi:nil="true"/><endDate>2014-08-31</endDate><startingDate>2012-09-01</startingDate></programRun><programRun><applicationDeadline xsi:nil="true"/><applicationDeadlineNonEU xsi:nil="true"/><endDate>2015-08-31</endDate><startingDate>2013-09-01</startingDate></programRun><programRun><applicationDeadline xsi:nil="true"/><applicationDeadlineNonEU xsi:nil="true"/><endDate>2016-08-31</endDate><startingDate>2014-09-01</startingDate></programRun><programStart><applicationDeadline xsi:nil='true'></applicationDeadline><applicationDeadlineNonEU xsi:nil='true'></applicationDeadlineNonEU><startingMonth>September</startingMonth></programStart></programOrganization><programFree><crohoName></crohoName><dl>nl</dl><studyClusterUvA>Aarde Natuur en Milieu</studyClusterUvA><studyClusterUvA>Beta</studyClusterUvA><studyClusterUvA>Techniek Ontwerp en Innovatie</studyClusterUvA><pp></pp><ps></ps><cq></cq><cp></cp><orgUnitLocationId><![CDATA[Amsterdam]]></orgUnitLocationId><facultyId><![CDATA[nwi]]></facultyId><targetMarket>nl</targetMarket><targetMarket>int</targetMarket><programPhase>initial</programPhase></programFree></program>
XML;