<?php
$xmlstr = <<<XML
<program xmlns="http://www.hodex.nl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.hodex.nl http://www.hodex.nl/hodex.xsd"><editor><![CDATA[editor@hodexer.nl]]></editor><expires>2012-02-13</expires><generator><![CDATA[hodexer]]></generator><hodexVersion><![CDATA[2.5.8]]></hodexVersion><lastEdited>2012-02-03</lastEdited><programClassification><crohoCode xsi:nil='true'></crohoCode><degree>certificate</degree><fieldOfEducation classification='SOI2006'>3112</fieldOfEducation><financing>government</financing><numerusFixus xsi:nil='true'></numerusFixus><orgUnitId>uva</orgUnitId><orgUnitLocation><![CDATA[Amsterdam]]></orgUnitLocation><programCredits>0</programCredits><programDuration>0</programDuration><programForm>full-time</programForm><programId>832</programId><programLevel>exchange program</programLevel><programType>regular</programType><startingYear>2012</startingYear><studyCluster>economics</studyCluster></programClassification><programContacts></programContacts><programCurriculum><instructionLanguage><languageCode>en</languageCode><percentage>100</percentage></instructionLanguage><percentageDistanceLearning xsi:nil='true'></percentageDistanceLearning><percentageNightEducation xsi:nil='true'></percentageNightEducation><sizeOfTutorialGroups xsi:nil='true'></sizeOfTutorialGroups><teachingTypesInCurriculumYear year='1'><teachingTypeInCurriculum><typeOfTeaching>theory</typeOfTeaching>
<percentage>0</percentage></teachingTypeInCurriculum><teachingTypeInCurriculum><typeOfTeaching>practice</typeOfTeaching>
<percentage>0</percentage></teachingTypeInCurriculum><teachingTypeInCurriculum><typeOfTeaching>self study</typeOfTeaching>
<percentage>0</percentage></teachingTypeInCurriculum></teachingTypesInCurriculumYear></programCurriculum><programDescriptions><programDescription xml:lang="en"><![CDATA[The Amsterdam Courses in Economics and Business (ACEB programme) is the name of a series of courses in Business, Business Economics, Economics and Quantitative Economics. These courses are fully taught in English, giving international (exchange) students the opportunity to get acquainted with Dutch academic education and with various aspects of the Dutch views on issues relating to business and economics. 

The programme is open to exchange students from universities of our international network and to independent, fee-paying students from other universities. Students can opt for taking either one semester or two semesters at the University of Amsterdam (UvA). 
]]></programDescription><programName xml:lang="en"><![CDATA[Exchange Programmes: Economics and Business]]></programName><programName xml:lang="nl"><![CDATA[Exchange Programmes: Economics and Business]]></programName><programSummary xml:lang="en"><![CDATA[The Amsterdam Courses in Economics and Business are a series of courses in English, giving foreign students the chance to experience a Dutch academic education relating to business and economics. ]]></programSummary><searchword xml:lang="nl"></searchword><webLink xml:lang="en">http://www.studeren.uva.nl/certificate_economics</webLink><webLink xml:lang="nl">http://www.studeren.uva.nl/certificate_economics</webLink></programDescriptions><programInternationalization><ErasmusMundusProgram>0</ErasmusMundusProgram><facilitationForeignScholarships xsi:nil='true'></facilitationForeignScholarships><foreignStay>0</foreignStay><maxForeignCredits xsi:nil='true'></maxForeignCredits><percentageForeignStudents xsi:nil='true'></percentageForeignStudents><percentageForeignTeachers xsi:nil='true'></percentageForeignTeachers><percentageStudentsAbroad xsi:nil='true'></percentageStudentsAbroad><percentageTeachersAbroad xsi:nil='true'></percentageTeachersAbroad><studyAbroad xsi:nil='true'></studyAbroad></programInternationalization><programRelations></programRelations><programOrganization><faculty xml:lang="en">Faculty of Economics and Business</faculty><faculty xml:lang="nl">faculteit Economie en Bedrijfskunde</faculty></programOrganization><programFree><crohoName></crohoName><dl>en</dl><studyClusterUvA>Economie en Ondernemen</studyClusterUvA><pp></pp><ps></ps><cq></cq><cp></cp><orgUnitLocationId><![CDATA[Amsterdam]]></orgUnitLocationId><facultyId><![CDATA[eb]]></facultyId><targetMarket>nl</targetMarket><targetMarket>int</targetMarket><programPhase>initial</programPhase></programFree></program>
XML;
?>