<<<XML
<program xmlns="http://www.hodex.nl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.hodex.nl http://www.hodex.nl/hodex.xsd"><editor><![CDATA[editor@hodexer.nl]]></editor><expires>2012-02-13</expires><generator><![CDATA[hodexer]]></generator><hodexVersion><![CDATA[2.5.8]]></hodexVersion><lastEdited>2012-02-03</lastEdited><programClassification><accreditation><accreditationDate>2015-02-08</accreditationDate><orgUnitCountry>nl</orgUnitCountry><orgUnitName><![CDATA[NVAO]]></orgUnitName><webLink xml:lang='nl'>http://www.nvao.net</webLink></accreditation><crohoCode>75059</crohoCode><degree>MSc</degree><fieldOfEducation classification='SOI2006'></fieldOfEducation><financing>private</financing><numerusFixus xsi:nil='true'></numerusFixus><orgUnitId>uva</orgUnitId><orgUnitLocation><![CDATA[Amsterdam]]></orgUnitLocation><programCredits>0</programCredits><programDuration unit="month">24</programDuration><programForm>part-time</programForm><programId>837</programId><programLevel>academic master</programLevel><programType>research</programType><startingYear>2012</startingYear><studyCluster>health care</studyCluster></programClassification><programContacts></programContacts><programCurriculum><instructionLanguage><languageCode>nl</languageCode><percentage>100</percentage></instructionLanguage><percentageDistanceLearning>0</percentageDistanceLearning><percentageNightEducation>0</percentageNightEducation><sizeOfTutorialGroups xsi:nil='true'></sizeOfTutorialGroups><teachingTypesInCurriculumYear year='1'><teachingTypeInCurriculum><typeOfTeaching>theory</typeOfTeaching>
<percentage>0</percentage></teachingTypeInCurriculum><teachingTypeInCurriculum><typeOfTeaching>practice</typeOfTeaching>
<percentage>0</percentage></teachingTypeInCurriculum><teachingTypeInCurriculum><typeOfTeaching>self study</typeOfTeaching>
<percentage>0</percentage></teachingTypeInCurriculum></teachingTypesInCurriculumYear></programCurriculum><programDescriptions><contentLink><contentSummary xml:lang="nl"><![CDATA[De opleiding biedt uitstekende perspectieven op de arbeidsmarkt.]]></contentSummary><contentType>website</contentType><subject>job perspective</subject><webLink xml:lang="nl"><![CDATA[http://studieadres.nl]]></webLink></contentLink><programDescription xml:lang="nl"><![CDATA[De advanced master Evidence Based Practice heeft tot doel ervaren paramedici, verpleegkundigen en bachelors in de geneeskunde academisch te vormen en te scholen als breed georiënteerde clinici die de wetenschappelijke literatuur systematisch doorzoeken, kritisch beoordelen en toepassen in hun vakgebied. 
academisch op te leiden tot klinisch wetenschappelijk onderzoeker (klinisch epidemioloog).
De tijdens de studie verkregen kennis en vaardigheden staan volledig in het teken van het wetenschappelijk onderbouwen van de klinische praktijk: Evidence Based Practice. 

In de opleiding wordt gebruikgemaakt van de methoden en technieken van de Klinische epidemiologie en Biostatistiek.

De opleiding wordt aangeboden door het Academisch Medisch Centrum (AMC-UvA), dat op het gebied van Evidence Based Practice intensief samenwerkt met de Department of Health Studies, University of York (Verenigd Koninkrijk).]]></programDescription><programName xml:lang="nl"><![CDATA[Evidence Based Practice]]></programName><programSummary xml:lang="nl"><![CDATA[Paramedici, verpleegkundigen en bachelors in de geneeskunde worden academisch gevormd en geschool als breed georiënteerde clinici en opgeleid tot klinisch wetenschappelijk onderzoeker.]]></programSummary><searchword xml:lang="nl"></searchword><webLink xml:lang="nl">http://www.studeren.uva.nl/msc-evidence-based-practice</webLink></programDescriptions><programInternationalization><ErasmusMundusProgram>0</ErasmusMundusProgram><facilitationForeignScholarships xsi:nil='true'></facilitationForeignScholarships><foreignStay xsi:nil='true'></foreignStay><maxForeignCredits xsi:nil='true'></maxForeignCredits><percentageForeignStudents xsi:nil='true'></percentageForeignStudents><percentageForeignTeachers xsi:nil='true'></percentageForeignTeachers><percentageStudentsAbroad xsi:nil='true'></percentageStudentsAbroad><percentageTeachersAbroad xsi:nil='true'></percentageTeachersAbroad><studyAbroad xsi:nil='true'></studyAbroad></programInternationalization><programRelations></programRelations><programOrganization><faculty xml:lang="en">Academic Medical Centre</faculty><faculty xml:lang="nl">faculteit der Geneeskunde (AMC-UvA)</faculty><programRun><applicationDeadline xsi:nil="true"/><applicationDeadlineNonEU xsi:nil="true"/><endDate>2014-08-31</endDate><startingDate>2012-09-01</startingDate></programRun><programRun><applicationDeadline xsi:nil="true"/><applicationDeadlineNonEU xsi:nil="true"/><endDate>2015-08-31</endDate><startingDate>2013-09-01</startingDate></programRun><programRun><applicationDeadline xsi:nil="true"/><applicationDeadlineNonEU xsi:nil="true"/><endDate>2016-08-31</endDate><startingDate>2014-09-01</startingDate></programRun><programStart><applicationDeadline xsi:nil='true'></applicationDeadline><applicationDeadlineNonEU xsi:nil='true'></applicationDeadlineNonEU><startingMonth>September</startingMonth></programStart><tuitionFee final='false'><amount>10500</amount><period>year</period><programForm>part-time</programForm><tuitionFeeRate>institutional</tuitionFeeRate><tuitionFeeType>part-time</tuitionFeeType><year>2013</year></tuitionFee><tuitionFee final='false'><amount>10500</amount><period>year</period><programForm>part-time</programForm><tuitionFeeRate>international</tuitionFeeRate><tuitionFeeType>non-EU-part-time</tuitionFeeType><year>2013</year></tuitionFee></programOrganization><programFree><crohoName></crohoName><dl>nl</dl><pp></pp><ps></ps><cq></cq><cp></cp><orgUnitLocationId><![CDATA[Amsterdam]]></orgUnitLocationId><facultyId><![CDATA[amc]]></facultyId><targetMarket>nl</targetMarket><programPhase>initial</programPhase></programFree></program>
XML;