<?php
$xmlstr = <<<XML
<program xmlns="http://www.hodex.nl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.hodex.nl http://www.hodex.nl/hodex.xsd"><editor><![CDATA[editor@hodexer.nl]]></editor><expires>2012-02-13</expires><generator><![CDATA[hodexer]]></generator><hodexVersion><![CDATA[2.5.8]]></hodexVersion><lastEdited>2012-02-03</lastEdited><programClassification><accreditation><accreditationDate>2017-04-11</accreditationDate><orgUnitCountry>nl</orgUnitCountry><orgUnitName><![CDATA[NVAO]]></orgUnitName><webLink xml:lang='nl'>http://www.nvao.net</webLink></accreditation><crohoCode>66402</crohoCode><degree>MSc</degree><fieldOfEducation classification='SOI2006'>3111</fieldOfEducation><financing>government</financing><numerusFixus xsi:nil='true'></numerusFixus><orgUnitId>uva</orgUnitId><orgUnitLocation><![CDATA[Amsterdam]]></orgUnitLocation><programCredits>60</programCredits><programDuration unit="month">12</programDuration><programForm>full-time</programForm><programId>1010</programId><programLevel>academic master</programLevel><programType>regular</programType><startingYear>2012</startingYear><studyCluster>economics</studyCluster></programClassification><programContacts></programContacts><programCurriculum><percentageDistanceLearning>0</percentageDistanceLearning><percentageNightEducation>0</percentageNightEducation><sizeOfTutorialGroups xsi:nil='true'></sizeOfTutorialGroups><teachingTypesInCurriculumYear year='1'><teachingTypeInCurriculum><typeOfTeaching>theory</typeOfTeaching>
<percentage>0</percentage></teachingTypeInCurriculum><teachingTypeInCurriculum><typeOfTeaching>practice</typeOfTeaching>
<percentage>0</percentage></teachingTypeInCurriculum><teachingTypeInCurriculum><typeOfTeaching>self study</typeOfTeaching>
<percentage>0</percentage></teachingTypeInCurriculum></teachingTypesInCurriculumYear></programCurriculum><programDescriptions><contentLink><contentSummary xml:lang="nl"><![CDATA[Ondanks de toenemende invloed van de automatisering in de Tax Compliance-praktijk van de belastingadvieskantoren, is de verwachting dat er de komende jaren meer banen zullen zijn voor fiscalisten met een MSc Tax Compliance, omdat juist de meest complexe aangiften zich niet in computerprogramma's laten vangen.]]></contentSummary><contentType>website</contentType><subject>job perspective</subject><webLink xml:lang="nl"><![CDATA[http://studieadres.nl]]></webLink></contentLink><programDescription xml:lang="nl"><![CDATA[Het zwaartepunt van de opleiding ligt bij het bestuderen van belastingrecht vanuit een economisch perspectief. De opleiding bewerkstelligt dit door het bieden van kennis en inzicht gericht op zowel de nationale als de internationale economische situatie en opvattingen.

Binnen de MSc Fiscale Economie kies je uit twee varianten:

- Fiscale economie
- Tax Compliance

In de (duale) Tax Compliance-variant  heb je de mogelijkheid om door middel van een verlengde studieduur twee werkperioden in je opleiding op te nemen.

De master Fiscale economie aan de UvA bestaat uit zowel fiscaal-juridische als economische vakken. Dit betekent dat je zowel college volgt aan de rechtenfaculteit in de Oudemanhuispoort, als aan de economische faculteit op het Roeterseiland. Door veel studenten wordt dit als een erg leuke afwisseling ervaren. Het past bovendien bij het karakter van de studie Fiscale economie die zich begeeft op het grensvlak van de economische en fiscaal-juridische wetenschap. Verder is Amsterdam natuurlijk bij uitstek geschikt om een passende baan te vinden in het bedrijfsleven bij (multi)nationale ondernemingen.]]></programDescription><programName xml:lang="nl"><![CDATA[Fiscale economie: Tax Compliance]]></programName><programName xml:lang="en"><![CDATA[Fiscale economie: Tax Compliance]]></programName><programSummary xml:lang="nl"><![CDATA[De eenjarige master Fiscale economie biedt een geïntegreerde combinatie van fiscaal-rechtelijke én fiscaal-economische vakken, die je opleidt tot een allround fiscalist. ]]></programSummary><searchword xml:lang="nl"></searchword><webLink xml:lang="nl">http://www.studeren.uva.nl/ma-fiscale-economie</webLink></programDescriptions><programInternationalization><ErasmusMundusProgram>0</ErasmusMundusProgram><facilitationForeignScholarships xsi:nil='true'></facilitationForeignScholarships><foreignStay xsi:nil='true'></foreignStay><maxForeignCredits xsi:nil='true'></maxForeignCredits><percentageForeignStudents xsi:nil='true'></percentageForeignStudents><percentageForeignTeachers xsi:nil='true'></percentageForeignTeachers><percentageStudentsAbroad xsi:nil='true'></percentageStudentsAbroad><percentageTeachersAbroad xsi:nil='true'></percentageTeachersAbroad><studyAbroad xsi:nil='true'></studyAbroad></programInternationalization><programRelations></programRelations><programOrganization><faculty xml:lang="en"></faculty><faculty xml:lang="nl"></faculty></programOrganization><programFree><crohoName></crohoName><dl>nl</dl><pp></pp><ps></ps><cq></cq><cp></cp><variant><programId><![CDATA[1010_dual]]></programId><variantType>dual</variantType></variant><orgUnitLocationId><![CDATA[Amsterdam]]></orgUnitLocationId><facultyId></facultyId><targetMarket>nl</targetMarket><programPhase>initial</programPhase></programFree></program>
XML;
?>