<<<XML
<program xmlns="http://www.hodex.nl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.hodex.nl http://www.hodex.nl/hodex.xsd"><editor><![CDATA[editor@hodexer.nl]]></editor><expires>2012-02-13</expires><generator><![CDATA[hodexer]]></generator><hodexVersion><![CDATA[2.5.8]]></hodexVersion><lastEdited>2012-02-03</lastEdited><programClassification><crohoCode xsi:nil='true'></crohoCode><degree>certificate</degree><fieldOfEducation classification='SOI2006'>5711</fieldOfEducation><financing>government</financing><numerusFixus xsi:nil='true'></numerusFixus><orgUnitId>uva</orgUnitId><orgUnitLocation><![CDATA[Amsterdam]]></orgUnitLocation><programCredits>0</programCredits><programDuration>0</programDuration><programForm>full-time</programForm><programId>843</programId><programLevel>exchange program</programLevel><programType>regular</programType><startingYear>2012</startingYear><studyCluster>technology</studyCluster><studyCluster>nature</studyCluster></programClassification><programContacts></programContacts><programCurriculum><instructionLanguage><languageCode>en</languageCode><percentage>100</percentage></instructionLanguage><percentageDistanceLearning xsi:nil='true'></percentageDistanceLearning><percentageNightEducation xsi:nil='true'></percentageNightEducation><sizeOfTutorialGroups xsi:nil='true'></sizeOfTutorialGroups><teachingTypesInCurriculumYear year='1'><teachingTypeInCurriculum><typeOfTeaching>theory</typeOfTeaching>
<percentage>0</percentage></teachingTypeInCurriculum><teachingTypeInCurriculum><typeOfTeaching>practice</typeOfTeaching>
<percentage>0</percentage></teachingTypeInCurriculum><teachingTypeInCurriculum><typeOfTeaching>self study</typeOfTeaching>
<percentage>0</percentage></teachingTypeInCurriculum></teachingTypesInCurriculumYear></programCurriculum><programDescriptions><programDescription xml:lang="en"><![CDATA[Bachelor's level
Nearly all courses on bachelor's level are taught in Dutch; students who would like to follow bachelor's courses therefore need to be fluent in the Dutch language.

Master's level
Nearly all master's courses in Science are taught in English and are therefore open to exchange students. Visit the UvA Course catalogue to search for courses.
]]></programDescription><programName xml:lang="en"><![CDATA[Exchange Programmes: Science]]></programName><programName xml:lang="nl"><![CDATA[Exchange Programmes: Science]]></programName><programSummary xml:lang="en"><![CDATA[Courses at bachelor's level are taught in Dutch; students who would therefore need to be fluent in Dutch.
Master's courses are taught in English and are therefore open to exchange students. 
]]></programSummary><searchword xml:lang="nl"></searchword><webLink xml:lang="en">http://www.studeren.uva.nl/exchange_science/</webLink><webLink xml:lang="nl">http://www.studeren.uva.nl/exchange_science/</webLink></programDescriptions><programInternationalization><ErasmusMundusProgram>0</ErasmusMundusProgram><facilitationForeignScholarships xsi:nil='true'></facilitationForeignScholarships><foreignStay xsi:nil='true'></foreignStay><maxForeignCredits xsi:nil='true'></maxForeignCredits><percentageForeignStudents xsi:nil='true'></percentageForeignStudents><percentageForeignTeachers xsi:nil='true'></percentageForeignTeachers><percentageStudentsAbroad xsi:nil='true'></percentageStudentsAbroad><percentageTeachersAbroad xsi:nil='true'></percentageTeachersAbroad><studyAbroad xsi:nil='true'></studyAbroad></programInternationalization><programRelations></programRelations><programOrganization><faculty xml:lang="en">Faculty of Science</faculty><faculty xml:lang="nl">faculteit der Natuurwetenschappen, Wiskunde en Informatica</faculty></programOrganization><programFree><crohoName></crohoName><dl>en</dl><studyClusterUvA>Beta</studyClusterUvA><studyClusterUvA>Techniek Ontwerp en Innovatie</studyClusterUvA><pp></pp><ps></ps><cq></cq><cp></cp><orgUnitLocationId><![CDATA[Amsterdam]]></orgUnitLocationId><facultyId><![CDATA[nwi]]></facultyId><targetMarket>nl</targetMarket><targetMarket>int</targetMarket><programPhase>initial</programPhase></programFree></program>
XML;