<?php
$xmlstr = <<<XML
<program xmlns="http://www.hodex.nl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.hodex.nl http://www.hodex.nl/hodex.xsd"><editor><![CDATA[editor@hodexer.nl]]></editor><expires>2012-02-13</expires><generator><![CDATA[hodexer]]></generator><hodexVersion><![CDATA[2.5.8]]></hodexVersion><lastEdited>2012-02-03</lastEdited><programClassification><crohoCode xsi:nil='true'></crohoCode><degree>certificate</degree><fieldOfEducation classification='SOI2006'>8141</fieldOfEducation><financing>government</financing><numerusFixus xsi:nil='true'></numerusFixus><orgUnitId>uva</orgUnitId><orgUnitLocation><![CDATA[Amsterdam]]></orgUnitLocation><programCredits>0</programCredits><programDuration>0</programDuration><programForm>full-time</programForm><programId>842</programId><programLevel>exchange program</programLevel><programType>regular</programType><startingYear>2012</startingYear><studyCluster>health care</studyCluster></programClassification><programContacts></programContacts><programCurriculum><instructionLanguage><languageCode>en</languageCode><percentage>100</percentage></instructionLanguage><percentageDistanceLearning xsi:nil='true'></percentageDistanceLearning><percentageNightEducation xsi:nil='true'></percentageNightEducation><sizeOfTutorialGroups xsi:nil='true'></sizeOfTutorialGroups><teachingTypesInCurriculumYear year='1'><teachingTypeInCurriculum><typeOfTeaching>theory</typeOfTeaching>
<percentage>0</percentage></teachingTypeInCurriculum><teachingTypeInCurriculum><typeOfTeaching>practice</typeOfTeaching>
<percentage>0</percentage></teachingTypeInCurriculum><teachingTypeInCurriculum><typeOfTeaching>self study</typeOfTeaching>
<percentage>0</percentage></teachingTypeInCurriculum></teachingTypesInCurriculumYear></programCurriculum><programDescriptions><programDescription xml:lang="en"><![CDATA[The Academic Medical Center of the UvA accepts a limited number of exchange students from international medical schools. International students can be accepted for periods known as 'blocks', research electives or elective clerkships.

Students must have completed at least three years of their medical education at their own medical school. Priority is given to applications from one of the official partner institutes of the UvA.


The Faculty of Dentistry of the UvA accepts exchange students from institutes with which the faculty holds an exchange agreement. These students can enrol for courses at the Academic Centre for Dentistry in Amsterdam (ACTA), usually for a short period during the summer months. Individual programmes are set up for those students, taking into account the student's specific wishes.

]]></programDescription><programName xml:lang="en"><![CDATA[Exchange Programmes: Medical Sciences and Dentistry]]></programName><programName xml:lang="nl"><![CDATA[Exchange Programmes: Medical Sciences and Dentistry]]></programName><programSummary xml:lang="en"><![CDATA[The Academic Medical Center and Faculty of Dentistry accept a limited number of exchange students.
]]></programSummary><searchword xml:lang="nl"></searchword><webLink xml:lang="en">http://www.studeren.uva.nl/exchange_courses/object.cfm/objectid=525368C3-0760-4794-A8F282268DA8E353</webLink><webLink xml:lang="nl">http://www.studeren.uva.nl/exchange_courses/object.cfm/objectid=525368C3-0760-4794-A8F282268DA8E353</webLink></programDescriptions><programInternationalization><ErasmusMundusProgram>0</ErasmusMundusProgram><facilitationForeignScholarships xsi:nil='true'></facilitationForeignScholarships><foreignStay xsi:nil='true'></foreignStay><maxForeignCredits xsi:nil='true'></maxForeignCredits><percentageForeignStudents xsi:nil='true'></percentageForeignStudents><percentageForeignTeachers xsi:nil='true'></percentageForeignTeachers><percentageStudentsAbroad xsi:nil='true'></percentageStudentsAbroad><percentageTeachersAbroad xsi:nil='true'></percentageTeachersAbroad><studyAbroad xsi:nil='true'></studyAbroad></programInternationalization><programRelations></programRelations><programOrganization><faculty xml:lang="en">Academic Medical Centre</faculty><faculty xml:lang="nl">faculteit der Geneeskunde (AMC-UvA)</faculty></programOrganization><programFree><crohoName></crohoName><dl>en</dl><studyClusterUvA>Gezondheid en Welzijn</studyClusterUvA><pp></pp><ps></ps><cq></cq><cp></cp><orgUnitLocationId><![CDATA[Amsterdam]]></orgUnitLocationId><facultyId><![CDATA[amc]]></facultyId><targetMarket>nl</targetMarket><targetMarket>int</targetMarket><programPhase>initial</programPhase></programFree></program>
XML;
?>