<?php
$xmlstr = <<<XML
<program xmlns="http://www.hodex.nl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.hodex.nl http://www.hodex.nl/hodex.xsd"><editor><![CDATA[editor@hodexer.nl]]></editor><expires>2011-12-09</expires><generator><![CDATA[hodexer]]></generator><hodexVersion><![CDATA[2.5.8]]></hodexVersion><lastEdited>2011-09-23</lastEdited><programClassification><accreditation><accreditationDate>2013-12-31</accreditationDate><orgUnitCountry>nl</orgUnitCountry><orgUnitName><![CDATA[NVAO]]></orgUnitName><webLink xml:lang='nl'>http://www.nvao.net</webLink></accreditation><crohoCode>60824</crohoCode><degree>MA</degree><fieldOfEducation classification='SOI2006'></fieldOfEducation><finalYear>2011</finalYear><financing>government</financing><numerusFixus xsi:nil='true'></numerusFixus><orgUnitId>uva</orgUnitId><orgUnitLocation><![CDATA[Amsterdam]]></orgUnitLocation><programCredits>60</programCredits><programDuration unit="month">12</programDuration><programForm>full-time</programForm><programId><![CDATA[1042]]></programId><programLevel>academic master</programLevel><programType>regular</programType><startingYear>2011</startingYear><studyCluster>language and culture</studyCluster></programClassification><programContacts></programContacts><programCurriculum><instructionLanguage><languageCode>nl</languageCode><percentage>100</percentage></instructionLanguage><percentageDistanceLearning xsi:nil='true'></percentageDistanceLearning><percentageNightEducation xsi:nil='true'></percentageNightEducation><sizeOfTutorialGroups xsi:nil='true'></sizeOfTutorialGroups><teachingTypesInCurriculumYear year='1'><teachingTypeInCurriculum><typeOfTeaching>theory</typeOfTeaching>
<percentage>0</percentage></teachingTypeInCurriculum><teachingTypeInCurriculum><typeOfTeaching>practice</typeOfTeaching>
<percentage>0</percentage></teachingTypeInCurriculum><teachingTypeInCurriculum><typeOfTeaching>self study</typeOfTeaching>
<percentage>0</percentage></teachingTypeInCurriculum></teachingTypesInCurriculumYear></programCurriculum><programDescriptions><contentLink><contentSummary xml:lang="nl"><![CDATA[Het mastertraject Islam in de moderne wereld leidt op tot het zelfstandig kunnen uitoefenen van een beroep op academisch niveau.

Het traject is geen theologische opleiding tot islamitisch geestelijk verzorger of godsdienstleraar, maar een godsdienstwetenschappelijke opleiding waarin de kritische studie van de islam als maatschappelijk verschijnsel centraal staat.]]></contentSummary><contentType>website</contentType><subject>job perspective</subject><webLink xml:lang="nl"><![CDATA[http://studieadres.nl]]></webLink></contentLink><programDescription xml:lang="nl"></programDescription><programName xml:lang="nl"><![CDATA[Theologie en religiewetenschappen: Islam in de moderne wereld]]></programName><programSummary xml:lang="nl"></programSummary><searchword xml:lang="nl"></searchword></programDescriptions><programInternationalization><ErasmusMundusProgram>0</ErasmusMundusProgram><facilitationForeignScholarships xsi:nil='true'></facilitationForeignScholarships><foreignStay xsi:nil='true'></foreignStay><maxForeignCredits xsi:nil='true'></maxForeignCredits><percentageForeignStudents xsi:nil='true'></percentageForeignStudents><percentageForeignTeachers xsi:nil='true'></percentageForeignTeachers><percentageStudentsAbroad xsi:nil='true'></percentageStudentsAbroad><percentageTeachersAbroad xsi:nil='true'></percentageTeachersAbroad><studyAbroad xsi:nil='true'></studyAbroad></programInternationalization><programRelations></programRelations><programOrganization><faculty xml:lang="en"></faculty><faculty xml:lang="nl"></faculty></programOrganization><programFree><dl>nl</dl><pp></pp><ps></ps><cq></cq><cp></cp><orgUnitLocationId><![CDATA[Amsterdam]]></orgUnitLocationId><facultyId></facultyId><targetMarket>nl</targetMarket><programPhase>initial</programPhase></programFree></program>
XML;
?>