<?php
$xmlstr = <<<XML
<program xmlns="http://www.hodex.nl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.hodex.nl http://www.hodex.nl/hodex.xsd"><editor><![CDATA[editor@hodexer.nl]]></editor><expires>2011-12-09</expires><generator><![CDATA[hodexer]]></generator><hodexVersion><![CDATA[2.5.8]]></hodexVersion><lastEdited>2011-12-05</lastEdited><programClassification><accreditation><accreditationDate>2017-05-09</accreditationDate><orgUnitCountry>nl</orgUnitCountry><orgUnitName><![CDATA[NVAO]]></orgUnitName><webLink xml:lang='nl'>http://www.nvao.net</webLink></accreditation><crohoCode>60323</crohoCode><degree>MSc</degree><fieldOfEducation classification='SOI2006'>5711</fieldOfEducation><finalYear>2011</finalYear><financing>government</financing><numerusFixus xsi:nil='true'></numerusFixus><orgUnitId>uva</orgUnitId><orgUnitLocation><![CDATA[Amsterdam]]></orgUnitLocation><programCredits>120</programCredits><programDuration unit="month">24</programDuration><programForm>full-time</programForm><programId><![CDATA[996]]></programId><programLevel>academic master</programLevel><programType>research</programType><startingYear>2011</startingYear><studyCluster>nature</studyCluster></programClassification><programContacts></programContacts><programCurriculum><percentageDistanceLearning>0</percentageDistanceLearning><percentageNightEducation>0</percentageNightEducation><sizeOfTutorialGroups xsi:nil='true'></sizeOfTutorialGroups><teachingTypesInCurriculumYear year='1'><teachingTypeInCurriculum><typeOfTeaching>theory</typeOfTeaching>
<percentage>0</percentage></teachingTypeInCurriculum><teachingTypeInCurriculum><typeOfTeaching>practice</typeOfTeaching>
<percentage>0</percentage></teachingTypeInCurriculum><teachingTypeInCurriculum><typeOfTeaching>self study</typeOfTeaching>
<percentage>0</percentage></teachingTypeInCurriculum></teachingTypesInCurriculumYear></programCurriculum><programDescriptions><contentLink><contentSummary xml:lang="nl"><![CDATA[The Master's programme in Brain and Cognitive Sciences provides its graduates with the necessary theoretical, intellectual and empirical tools to pursue an academic career (PhD programme) in cognitive and neurosciences or in a related discipline. In addition to an academic career, graduates of the Brain and Cognitive Sciences programme also find work in applied research.]]></contentSummary><contentType>website</contentType><subject>job perspective</subject><webLink xml:lang="nl"><![CDATA[http://studieadres.nl]]></webLink></contentLink><programDescription xml:lang="nl"><![CDATA[It provides courses and research opportunities into vision and perception, learning and memory, thinking and problem-solving, knowledge representation, action control and language.

The track focuses on the processes involved in human cognitive behaviour, in particular memory, language and action control. The aim is to better understand the architecture and evolution of the cognitive system and its role in reasoning and communication.

Students in this track can choose to specialise in more psychologically-oriented areas (such as human memory, attention, perception and action) as well as in areas that are more closely tied to linguistics (e.g. psycholinguistics) and computer science (e.g. artificial intelligence).]]></programDescription><programName xml:lang="nl"><![CDATA[Brain and Cognitive Science: Cognitive Science]]></programName><programName xml:lang="en"><![CDATA[Brain and Cognitive Science: Cognitive Science]]></programName><programSummary xml:lang="nl"><![CDATA[The Cognitive Science track is characterised by its strong interdisciplinary focus on cognition and by its emphasis on gaining a broad overview of mind/brain theories and knowledge.]]></programSummary><searchword xml:lang="nl"></searchword></programDescriptions><programInternationalization><ErasmusMundusProgram>0</ErasmusMundusProgram><facilitationForeignScholarships xsi:nil='true'></facilitationForeignScholarships><foreignStay xsi:nil='true'></foreignStay><maxForeignCredits xsi:nil='true'></maxForeignCredits><percentageForeignStudents xsi:nil='true'></percentageForeignStudents><percentageForeignTeachers xsi:nil='true'></percentageForeignTeachers><percentageStudentsAbroad xsi:nil='true'></percentageStudentsAbroad><percentageTeachersAbroad xsi:nil='true'></percentageTeachersAbroad><studyAbroad xsi:nil='true'></studyAbroad></programInternationalization><programRelations></programRelations><programOrganization><faculty xml:lang="en">Faculty of Science</faculty><faculty xml:lang="nl">faculteit der Natuurwetenschappen, Wiskunde en Informatica</faculty></programOrganization><programFree><dl>nl</dl><pp></pp><ps></ps><cq></cq><cp></cp><orgUnitLocationId><![CDATA[Amsterdam]]></orgUnitLocationId><facultyId><![CDATA[nwi]]></facultyId><targetMarket>nl</targetMarket><targetMarket>int</targetMarket><programPhase>initial</programPhase></programFree></program>
XML;
?>